### ISSUE TITLE
Register Form Validation

### ISSUE THREAD

**Issue by sabin-thapa** [kucc1997/kucc-website#37]
Validate the input fields in the register form

**Comment by tanishk-23** [comment]
@sabin-thapa Can you assign this issue to me?

**Comment by erwinschrodinger1** [comment]
Seems like @tanishk-23  is out of range can you assign this to me @sabin-thapa ?

**Comment by sabin-thapa** [comment]
> Seems like @tanishk-23 is out of range can you assign this to me @sabin-thapa ?

Done :heavy_check_mark:

**Comment by harshilsarariya** [comment]
@sabin-thapa  Can you assign this issue to me?
