### ISSUE TITLE
Our Team Section

### ISSUE THREAD

**Issue by sabint017** [kucc1997/kucc-website#4]
Includes:

- Executive Committee
- Advisory Board
- Community Co-ordinators
- Community Members (Active)
> Should include the name, photo, and designation.
> Ref: http://kucc.ku.edu.np/community-coordinators/

**Comment by Amarmandal** [comment]
WIP

**Comment by sabint017** [comment]
@Amarmandal I will add the image assets tomorrow. Make sure to pull the upstream branch :D

**Comment by Amarmandal** [comment]
@sabint017 sure.
