### ISSUE TITLE
fix: header/navbar bug

### ISSUE THREAD

**Issue by sabin-thapa** [kucc1997/kucc-website#56]
On hovering over the _Our Team_ section on the Header of the website, the expanded content gets hidden behind the image as shown:
![image](https://user-images.githubusercontent.com/51270026/197558875-e3bc1cc3-ff61-4d3f-82e0-5765cc4c0282.png)

Solution: The content should be above the background.

**Comment by Keerthivardhan1** [comment]
It is related to z factor of the image when we hover I can solve can you assign this issue to me

**Comment by avezqureshi14** [comment]
Hey I have quick and easy solution for this, can you assign me this I will fix the bug and make the pull request in few minutes of assigning me

**Comment by riddhitech** [comment]
Please assign me this issue.

**Comment by dissyulina** [comment]
Hi @riddhitech , sorry I think I won't be doing this task anymore. I will remove myself from the assignees list. Thanks and have a great day!

**Comment by abhiyandhakal** [comment]
This has been fixed now.
