### ISSUE TITLE
Apply To Be a Member in footer not working

### ISSUE THREAD

**Issue by NotSugat** [kucc1997/kucc-website#70]
footer links should be absolute instead of relative
way to reproduce:
when clicking apply to member in footer it redirects to 
https://kucc.ku.edu.np/https://forms.gle/Y5vHobrCDVx2fPMaA
instead of 
https://forms.gle/Y5vHobrCDVx2fPMaA

**Comment by abhiyandhakal** [comment]
This issue has been fixed and merged into main branch.
