### ISSUE TITLE
Not Found Page should be added

### ISSUE THREAD

**Issue by kausik10** [kucc1997/kucc-website#71]
If you navigate to any non existing path;; for example : https://kucc.ku.edu.np/abc
There should be a page displaying PageNotFound or something like that
But instead nothing is rendered
![KUCC_BUGG](https://github.com/kucc1997/kucc-website/assets/97453660/c29d36e0-54b8-402e-9744-48a5ee2fccc4)

**Comment by razzat008** [comment]
working on it
